version: '3'
services:
  lifetracker: 
    image: lifetracker:latest
    container_name: lifetracker
    # restart: always
    environment:
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    volumes:
      - "<location of instance folder on disk>:/lifetracker"
